# Generated by Django 5.2.17 on 2026-09-24 01:14

import django.db.models.deletion
import identity.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20, validators=[identity.models.validate_phone_number])),
                ('is_active', models.BooleanField(default=True, help_text='Unset to deactivate an account without deleting it.')),
                ('is_verified', models.BooleanField(default=False, help_text='Email ownership has been confirmed. Not set automatically on registration.')),
                ('is_staff', models.BooleanField(default=False, help_text='Can access the Django admin site.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', identity.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ExternalIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(help_text="e.g. 'google'.", max_length=32)),
                ('provider_subject', models.CharField(help_text="The provider's stable unique identifier for this identity (e.g. Google's `sub` claim). Opaque to us; never assume a format.", max_length=255)),
                ('email', models.EmailField(help_text='The email the provider reported at link time. Informational - the platform identity is `user`, not this address.', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'external identities',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_subject'), name='unique_external_identity_per_provider')],
            },
        ),
    ]
