# Generated by Django 5.2.17 on 2026-09-24 16:44

import identity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_refreshsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[identity.models.validate_phone_number]),
        ),
    ]
