# Generated by Django 5.2.17 on 2026-09-25 14:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


PERMISSION_DEFINITIONS = (
    ('organization.view', 'View organization', 'View the organization workspace and its details.'),
    ('organization.create', 'Create organization', 'Create a new organization workspace.'),
    ('organization.update', 'Update organization', 'Update organization details.'),
    ('organization.members.view', 'View organization members', 'View active memberships in the organization.'),
    ('organization.members.manage', 'Manage organization members', 'Manage organization memberships and their roles.'),
)


def create_permissions(apps, schema_editor):
    permission_model = apps.get_model('organizations', 'Permission')
    database_alias = schema_editor.connection.alias
    for code, name, description in PERMISSION_DEFINITIONS:
        permission_model.objects.using(database_alias).get_or_create(
            code=code,
            defaults={'name': name, 'description': description},
        )


def migrate_existing_organizations(apps, schema_editor):
    organization_model = apps.get_model('organizations', 'Organization')
    membership_model = apps.get_model('organizations', 'Membership')
    role_model = apps.get_model('organizations', 'Role')
    role_permission_model = apps.get_model('organizations', 'RolePermission')
    membership_role_model = apps.get_model('organizations', 'MembershipRole')
    permission_model = apps.get_model('organizations', 'Permission')
    database_alias = schema_editor.connection.alias
    permissions = permission_model.objects.using(database_alias).all()

    organizations = organization_model.objects.using(database_alias).all().order_by('pk')
    for organization in organizations:
        role, _ = role_model.objects.using(database_alias).get_or_create(
            organization=organization,
            slug='owner',
            defaults={
                'name': 'Owner',
                'description': 'Full access to the organization foundation.',
                'is_system': True,
            },
        )
        for permission in permissions:
            role_permission_model.objects.using(database_alias).get_or_create(
                role=role,
                permission=permission,
            )
        membership = (
            membership_model.objects.using(database_alias)
            .filter(organization=organization)
            .order_by('created_at', 'pk')
            .first()
        )
        if membership is not None:
            membership_role_model.objects.using(database_alias).get_or_create(
                membership=membership,
                role=role,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Permission codes must use lowercase dot-separated segments.', regex='^[a-z][a-z0-9_]*(?:\\.[a-z][a-z0-9_]*)+$')])),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organizations.organization')),
            ],
            options={
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_roles', to='organizations.membership')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_roles', to='organizations.role')),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='organizations.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='organizations.role')),
            ],
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['organization', 'slug'], name='organizatio_organiz_7bfcae_idx'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='unique_role_slug_per_organization'),
        ),
        migrations.AddIndex(
            model_name='membershiprole',
            index=models.Index(fields=['membership', 'role'], name='organizatio_members_0bd9a8_idx'),
        ),
        migrations.AddIndex(
            model_name='membershiprole',
            index=models.Index(fields=['role', 'membership'], name='organizatio_role_id_4402d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='membershiprole',
            constraint=models.UniqueConstraint(fields=('membership', 'role'), name='unique_role_per_membership'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='unique_permission_per_role'),
        ),
        migrations.RunPython(create_permissions, migrate_existing_organizations),
    ]
